version: '3.3'

services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/roll-dice-dnd:/data
    restart: unless-stopped
    command: [ "python3", "./main.py" ]
