version: '3.3'

services:
  bots:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/roll-dice-dnd:/app/data
    restart: unless-stopped
    stop_grace_period: 30s
    env_file:
      - ./src/.env
    command: ["/app/start-bots.sh"]