version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "8080:15672"
      - "15672:15672"
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'celery', '-A', 'tasks', 'worker', '-l', 'INFO', '-Q', 'dices' ]
    restart: unless-stopped
    environment:
      - BROKER_URL=amqp://rabbitmq:5672//
      - C_FORCE_ROOT=true
    depends_on:
      - rabbitmq

  discord:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - BROKER_URL=amqp://rabbitmq:5672//
    command: [ "python", "./discord_client.py" ]
    depends_on:
      - celery
