version: '3.3'

services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/roll-dice-dnd:/data
    restart: unless-stopped
    command: [ "poetry", "run", "python3", "/app/src/main.py" ]